-- Seed kata untuk Minggu 1–5 (starter deterministik, ~60 kata).
-- Perluas dengan scripts/seed-words.ts (batch LLM) kapan pun.
insert into words (text, translation_id, phonetic, part_of_speech, chunk, example_en, example_id, theme_week, frequency_rank, tense_focus) values
-- Minggu 1: kata inti + "to be"
('I', 'saya', '/aɪ/', 'pronoun', 'I am', 'I am a student.', 'Saya seorang pelajar.', 1, 1, 'none'),
('you', 'kamu', '/juː/', 'pronoun', 'you are', 'You are my friend.', 'Kamu temanku.', 1, 2, 'none'),
('this', 'ini', '/ðɪs/', 'pronoun', 'this is', 'This is a book.', 'Ini sebuah buku.', 1, 20, 'none'),
('is', 'adalah', '/ɪz/', 'verb', 'he is', 'She is happy.', 'Dia bahagia.', 1, 7, 'none'),
('am', 'adalah (saya)', '/æm/', 'verb', 'I am', 'I am tired.', 'Saya lelah.', 1, 30, 'none'),
('are', 'adalah (kamu/mereka)', '/ɑːr/', 'verb', 'they are', 'They are here.', 'Mereka di sini.', 1, 12, 'none'),
('a', 'sebuah', '/ə/', 'article', 'a book', 'I have a pen.', 'Saya punya sebuah pena.', 1, 5, 'none'),
('the', '(kata sandang)', '/ðə/', 'article', 'the house', 'The house is big.', 'Rumah itu besar.', 1, 1, 'none'),
('my', 'milikku', '/maɪ/', 'pronoun', 'my name', 'My name is Andi.', 'Namaku Andi.', 1, 40, 'none'),
('name', 'nama', '/neɪm/', 'noun', 'my name', 'My name is Sari.', 'Namaku Sari.', 1, 60, 'none'),
('yes', 'ya', '/jɛs/', 'adverb', 'yes please', 'Yes, I do.', 'Ya, saya mau.', 1, 80, 'none'),
('no', 'tidak', '/noʊ/', 'adverb', 'no thanks', 'No, thank you.', 'Tidak, terima kasih.', 1, 45, 'none'),
('good', 'baik', '/ɡʊd/', 'adjective', 'good morning', 'Good morning!', 'Selamat pagi!', 1, 55, 'none'),
('friend', 'teman', '/frɛnd/', 'noun', 'my friend', 'You are my friend.', 'Kamu temanku.', 1, 90, 'none'),
-- Minggu 2: kegiatan harian (Present Simple)
('eat', 'makan', '/iːt/', 'verb', 'eat breakfast', 'I eat rice every day.', 'Saya makan nasi setiap hari.', 2, 42, 'presentSimple'),
('go', 'pergi', '/ɡoʊ/', 'verb', 'go to work', 'I go to work.', 'Saya pergi bekerja.', 2, 15, 'presentSimple'),
('work', 'bekerja', '/wɜːrk/', 'verb', 'go to work', 'I work every day.', 'Saya bekerja setiap hari.', 2, 35, 'presentSimple'),
('sleep', 'tidur', '/sliːp/', 'verb', 'sleep early', 'I sleep at night.', 'Saya tidur di malam hari.', 2, 120, 'presentSimple'),
('drink', 'minum', '/drɪŋk/', 'verb', 'drink water', 'I drink water.', 'Saya minum air.', 2, 110, 'presentSimple'),
('read', 'membaca', '/riːd/', 'verb', 'read a book', 'I read a book.', 'Saya membaca buku.', 2, 70, 'presentSimple'),
('like', 'suka', '/laɪk/', 'verb', 'I like', 'I like coffee.', 'Saya suka kopi.', 2, 25, 'presentSimple'),
('want', 'ingin', '/wɑːnt/', 'verb', 'I want', 'I want food.', 'Saya ingin makanan.', 2, 22, 'presentSimple'),
('have', 'punya', '/hæv/', 'verb', 'I have', 'I have a car.', 'Saya punya mobil.', 2, 8, 'presentSimple'),
('live', 'tinggal', '/lɪv/', 'verb', 'live in', 'I live in Aceh.', 'Saya tinggal di Aceh.', 2, 130, 'presentSimple'),
('speak', 'berbicara', '/spiːk/', 'verb', 'speak English', 'I speak English.', 'Saya berbicara bahasa Inggris.', 2, 140, 'presentSimple'),
('water', 'air', '/ˈwɔːtər/', 'noun', 'drink water', 'I drink water every day.', 'Saya minum air setiap hari.', 2, 100, 'presentSimple'),
('rice', 'nasi', '/raɪs/', 'noun', 'eat rice', 'I eat rice.', 'Saya makan nasi.', 2, 300, 'presentSimple'),
('every', 'setiap', '/ˈɛvri/', 'adjective', 'every day', 'I work every day.', 'Saya bekerja setiap hari.', 2, 65, 'presentSimple'),
-- Minggu 3: sedang terjadi (Present Continuous)
('now', 'sekarang', '/naʊ/', 'adverb', 'right now', 'I am eating now.', 'Saya sedang makan sekarang.', 3, 33, 'presentContinuous'),
('today', 'hari ini', '/təˈdeɪ/', 'adverb', 'today is', 'I am working today.', 'Saya sedang bekerja hari ini.', 3, 75, 'presentContinuous'),
('reading', 'sedang membaca', '/ˈriːdɪŋ/', 'verb', 'am reading', 'I am reading a book.', 'Saya sedang membaca buku.', 3, 200, 'presentContinuous'),
('eating', 'sedang makan', '/ˈiːtɪŋ/', 'verb', 'am eating', 'She is eating rice.', 'Dia sedang makan nasi.', 3, 210, 'presentContinuous'),
('going', 'sedang pergi', '/ˈɡoʊɪŋ/', 'verb', 'am going', 'I am going home.', 'Saya sedang pergi pulang.', 3, 50, 'presentContinuous'),
('working', 'sedang bekerja', '/ˈwɜːrkɪŋ/', 'verb', 'am working', 'He is working now.', 'Dia sedang bekerja sekarang.', 3, 180, 'presentContinuous'),
('doing', 'sedang melakukan', '/ˈduːɪŋ/', 'verb', 'am doing', 'What are you doing?', 'Kamu sedang apa?', 3, 90, 'presentContinuous'),
('watching', 'sedang menonton', '/ˈwɑːtʃɪŋ/', 'verb', 'am watching', 'I am watching TV.', 'Saya sedang menonton TV.', 3, 220, 'presentContinuous'),
('home', 'rumah', '/hoʊm/', 'noun', 'go home', 'I am going home.', 'Saya sedang pulang.', 3, 85, 'presentContinuous'),
('book', 'buku', '/bʊk/', 'noun', 'a book', 'I am reading a book.', 'Saya sedang membaca buku.', 3, 95, 'presentContinuous'),
-- Minggu 4: kemarin (Past Simple)
('yesterday', 'kemarin', '/ˈjɛstərdeɪ/', 'adverb', 'yesterday I', 'Yesterday I went home.', 'Kemarin saya pulang.', 4, 160, 'pastSimple'),
('went', 'pergi (lampau)', '/wɛnt/', 'verb', 'went to', 'I went to work.', 'Saya pergi bekerja.', 4, 170, 'pastSimple'),
('ate', 'makan (lampau)', '/eɪt/', 'verb', 'ate rice', 'I ate rice.', 'Saya makan nasi.', 4, 175, 'pastSimple'),
('was', 'adalah (lampau)', '/wɒz/', 'verb', 'I was', 'I was happy.', 'Saya bahagia.', 4, 18, 'pastSimple'),
('were', 'adalah (lampau, jamak)', '/wɜːr/', 'verb', 'you were', 'You were here.', 'Kamu tadi di sini.', 4, 48, 'pastSimple'),
('did', 'melakukan (lampau)', '/dɪd/', 'verb', 'did you', 'I did my work.', 'Saya mengerjakan tugasku.', 4, 38, 'pastSimple'),
('saw', 'melihat (lampau)', '/sɔː/', 'verb', 'I saw', 'I saw a cat.', 'Saya melihat kucing.', 4, 185, 'pastSimple'),
('made', 'membuat (lampau)', '/meɪd/', 'verb', 'made food', 'I made food.', 'Saya membuat makanan.', 4, 190, 'pastSimple'),
('drank', 'minum (lampau)', '/dræŋk/', 'verb', 'drank water', 'I drank water.', 'Saya minum air.', 4, 240, 'pastSimple'),
('slept', 'tidur (lampau)', '/slɛpt/', 'verb', 'slept early', 'I slept early.', 'Saya tidur lebih awal.', 4, 250, 'pastSimple'),
-- Minggu 5: nanti (Future)
('tomorrow', 'besok', '/təˈmɑːroʊ/', 'adverb', 'tomorrow I', 'Tomorrow I will work.', 'Besok saya akan bekerja.', 5, 165, 'future'),
('will', 'akan', '/wɪl/', 'verb', 'will go', 'I will go home.', 'Saya akan pulang.', 5, 28, 'future'),
('plan', 'rencana', '/plæn/', 'verb', 'plan to', 'I plan to study.', 'Saya berencana belajar.', 5, 155, 'future'),
('next', 'berikutnya', '/nɛkst/', 'adjective', 'next week', 'Next week I will travel.', 'Minggu depan saya akan pergi.', 5, 78, 'future'),
('buy', 'membeli', '/baɪ/', 'verb', 'buy food', 'I will buy food.', 'Saya akan membeli makanan.', 5, 105, 'future'),
('meet', 'bertemu', '/miːt/', 'verb', 'meet a friend', 'I will meet my friend.', 'Saya akan bertemu teman.', 5, 115, 'future'),
('study', 'belajar', '/ˈstʌdi/', 'verb', 'study English', 'I will study English.', 'Saya akan belajar bahasa Inggris.', 5, 88, 'future'),
('week', 'minggu', '/wiːk/', 'noun', 'next week', 'Next week is busy.', 'Minggu depan sibuk.', 5, 68, 'future')
on conflict (text) do nothing;
